---
version: "2"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: wordpress
    restart: unless-stopped
    mem_swappiness: -1
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=100
      - PGID=1027
      - TZ=America/Chicago
      - URL=tomthegreat.com
      - SUBDOMAINS=wildcard
      - VALIDATION=http
      - DNSPLUGIN=cloudflare
    volumes:
      - /docker/wordpress/config:/config
      - /docker/wordpress/html:/var/www/default
    network_mode: bridge
    ports:
      - 443:443
      - 80:80
    depends_on:
      - mariadb
